### ISSUE TITLE
Python35 is not available in CentOS7

### ISSUE THREAD

**Issue by zealseeker** [protwis/protwis_prod_conf#1]
I installed CentOS 7 in virtualbox and successfully installed "epel-release git puppet"
However, when I ran puppet, I found a lot of errors caused by python. Then I tried to use "yum search python3" and found that python35 (as well as python35-devel) is not available.

So I wonder whether I can install python36 or python34. And if so, I have to modify the pp files, which seems to be troublesome since the path or something else have to be changed (e.g. /usr/bin/python3.5 -> /usr/bin/python3.6). 
Is there any better way? For example adding other repositories?

------------
hostfile of yum: base, epel, extras, updates

**Comment by cmunk** [comment]
I think you can make a fork perhaps of the puppet that forces Python3.4?
